parameters:
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  CRAN: 'https://cloud.r-project.org'
  coverage: true
  env: {}

jobs:
  - job: 'Linux'
    variables:
      CRAN: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      TZ: UTC
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      matrix:
        R-release:
          containerImage: rstudio/r-base:focal
        R-release-4.0:
          containerImage: rstudio/r-base:4.0-focal
        R-dev:
          containerImage: rstudio/r-base:devel-focal
    container: $[ variables['containerImage'] ]
    steps:
      - template: templates/r-setup-linux.yml
      - template: templates/pkg-workflow.yml
        parameters:
          coverage: false

  - job: 'Windows'
    variables:
      CRAN: ${{parameters.CRAN}}
      R_LIBS_USER: ${{parameters.R_LIBS_USER}}
      CI: true
      ${{ insert }}: ${{ parameters.env }}
    pool:
      vmImage: 'VS2017'
    steps:
      - template: templates/r-setup-windows.yml
      - template: templates/pkg-workflow.yml
        parameters:
          args: "c('--no-manual', '--no-multiarch')"
          coverage: false
          cache: false
